### PR TITLE
Update base image to Ubuntu focal (19.10) and use system clang

### PR DESCRIPTION
**Pull request by msimberg**
Gives us a newer clang (9) and CMake (3.15).

### CODE REVIEW

**Comment by hkaiser** [comment]
Will that also update clang-format? That might cause some reformatting...

**Comment by msimberg** [comment]
Yes, and it may... I'll check the formatting before we merge this.

**Comment by msimberg** [comment]
It does change the formatting (a bit...). I've changed it back to `clang-format` 8. We can update that separately.

**Comment by hkaiser** [comment]
@msimberg remember those commented changes to the `.clang-format` file I had on one of the (now closed) PR's? I think those should take care of the differences in formatting between V8 and V9.

**Comment by msimberg** [comment]
> @msimberg remember those commented changes to the `.clang-format` file I had on one of the (now closed) PR's? I think those should take care of the differences in formatting between V8 and V9.

I do! I'll check if they do exactly that. Thanks!

**Comment by hkaiser** [comment]
@parsa Once this is merged we can remove the installation of that specific cmake version from our Phylanx builds.

**Comment by msimberg** [comment]
Ok to merge?

**Pull request merged**
