### PR TITLE
updated sphinx version

### PR DESCRIPTION
**Pull request by emiliostassios**
Updated the doc_requirments.txt  to the more recent versions of sphinx and related packages that are required to build HPX with documentation.

### CODE REVIEW

**Comment by hkaiser** [comment]
@emiliostassios Could you please bump the version of the docker image generated as described here: https://github.com/STEllAR-GROUP/docker_build_env/blob/master/hpx_build_env/Dockerfile#L11-L15?

**Comment by dimitraka** [comment]
I am updating the sphinx version in the documentation. Can we get this merged too?

Please make sure that  if you use the new docker image HPX is built successfully

**Comment by emiliostassios** [comment]
I thought I created a pull request for this.  My bad, must have slipped
my mind.
Doing it asap.

**Comment by hkaiser** [comment]
Close as duplicate of #65

**Pull request closed without merging**
