### PR TITLE
build: install sphinxcontrib-bibtex using pip

### PR DESCRIPTION
**Pull request by bhumitattarde**
This change installs `sphinxcontrib-bibtex` using `pip`.
Refer to https://github.com/STEllAR-GROUP/hpx/pull/5626.

### CODE REVIEW

**Comment by hkaiser** [comment]
Thanks! Could you please increment the version number for the generated docker image as well - here: https://github.com/STEllAR-GROUP/docker_build_env/blob/master/.circleci/config.yml#L15?

**Comment by bhumitattarde** [comment]
> Thanks! Could you please increment the version number for the generated docker image as well - here: https://github.com/STEllAR-GROUP/docker_build_env/blob/master/.circleci/config.yml#L15?

I apologize, I missed the comment in the Dockerfile. Should be fine now.

**Comment by msimberg** [comment]
@bhumitattarde unfortunately the version number has to be changed in two more locations (changes to put it in just one location are welcome, but not required for this PR): https://github.com/STEllAR-GROUP/docker_build_env/blob/99ef754e543e644e27e50551d2ff8e7e9426c48b/.circleci/config.yml#L52 and https://github.com/bhumitattarde/docker_build_env/blob/99ef754e543e644e27e50551d2ff8e7e9426c48b/hip_hpx_build_env/Dockerfile#L6.

**Comment by bhumitattarde** [comment]
@msimberg check now?

**Review by msimberg — APPROVED** [review]
Thanks!

**Pull request merged**
