### PR TITLE
Add iwyu to docker image

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by K-ballo** [comment]
Something is wrong, the iwyu version corresponds to `clang-8.0.1` but the image has `clang-9.0.0`. As a result, iwyu can't find clang's built-in headers out of the box.

See https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-install

**Comment by K-ballo** [comment]
Glob matching in iwyu is suboptimal before version 0.14, as it only works with absolute path. We should be able to work with it within a specific CI build, but we need to keep it in mind.

**Comment by msimberg** [comment]
Thanks for checking @K-ballo. In that case we're probably better off installing a more recent version ourselves. I'll try to update this in the next few days.

**Comment by msimberg** [comment]
@K-ballo could you give this image a try: https://hub.docker.com/layers/simberg/hpx-dev/iwyu-0.14/images/sha256-68ce550892ae77b7090208b0ea9321840bc7a68877ad16cd5925bb58aa6b805d?context=repo (`docker pull simberg/hpx-dev:iwyu-0.14` should do it I hope)? It's now using clang 10 and iwyu 0.14. The newest Ubuntu (20.10) would have clang 11 which would work with iwyu master, but I had trouble with other packages on 20.10, so I hope 0.14 is ok. As far as I can tell the paths are now ok.

**Comment by K-ballo** [comment]
> @K-ballo could you give this image a try: https://hub.docker.com/layers/simberg/hpx-dev/iwyu-0.14/images/sha256-68ce550892ae77b7090208b0ea9321840bc7a68877ad16cd5925bb58aa6b805d?context=repo

IWYU works as expected on that image.

**Pull request merged**
