### PR TITLE
Updated versions doc requirments

### PR DESCRIPTION
**Pull request by emiliostassios**

### CODE REVIEW

**Comment by gonidelis** [comment]
I love this work

**Comment by hkaiser** [comment]
@emiliostassios does this supersede #64?

**Review by hkaiser — APPROVED** [review]

**Comment by emiliostassios** [comment]
> @emiliostassios does this supersede #64?

@hkaiser yes, it does.

**Comment by hkaiser** [comment]
@emiliostassios now that the new image was built, we need to update the .cicleci/config.yml here: https://github.com/STEllAR-GROUP/hpx/blob/cd8d65b50570ecc9ab7fcf48c4f4dd086c59e57d/.circleci/config.yml#L14 to refer to it.

**Pull request merged**
